### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by immadisairaj** [amfoss/temple-app#119]
**Describe the chore**
Replace the old screenshots with new UI, the workflow and license badge

**Would you like to work on the issue?**
No

**Comment by yashk2000** [comment]
We will update screenshots in the readme once the proper functionalities are implemented in the new UI. Currently, it is just a skeleton. We have yet to port the code from the old UI portion to the new UI. Once all the app functionalities are ported to the new UI, we will proceed with this issue.

**Comment by ajay-prabhakar** [comment]
Anyone can take up this issue now😄

**Comment by ajay-prabhakar** [comment]
As we migrated to GitLab I will open the issue there,  I am closing this issue 
If there any queries we can reopen this
