### ISSUE TITLE
Create layouts for Add Pooja and confirm details

### ISSUE THREAD

**Issue by ajay-prabhakar** [amfoss/temple-app#121]
**Describe the chore**

create the layouts for [Add Pooja](https://xd.adobe.com/spec/f4a98c6f-d6f6-4eae-5744-047ad958b58b-8298/screen/0366c3e4-a218-4988-89e2-81e92e808fb2/Add-pooja) and [Confirm details](https://xd.adobe.com/spec/f4a98c6f-d6f6-4eae-5744-047ad958b58b-8298/screen/09e6a9bb-2e53-47f9-9d45-1bfe212637ff/Add-pooja-Confirm) please fallow the mockups while creating any view

**Additional**
I would recommend to use this [Material Text feild](https://github.com/florent37/MaterialTextField) for editTexts

**Would you like to work on the issue?** (Yes/No)
No

**Comment by ashandilya** [comment]
Can I work on this?

**Comment by vchrombie** [comment]
Sorry, @ashandilya. We had @gopikaharikumar assigned for this already. Please see for any unassigned issues. :slightly_smiling_face:
