### ISSUE TITLE
Create layouts for Add Donation and Confirm details

### ISSUE THREAD

**Issue by ajay-prabhakar** [amfoss/temple-app#122]
**Describe the chore**

create the layouts for [Add Donation](https://xd.adobe.com/spec/f4a98c6f-d6f6-4eae-5744-047ad958b58b-8298/screen/bf076f86-b29e-4b7d-897b-c3dbbf33b799/Add-donation) and [Confirm details](https://xd.adobe.com/spec/f4a98c6f-d6f6-4eae-5744-047ad958b58b-8298/screen/09e6a9bb-2e53-47f9-9d45-1bfe212637ff/Add-pooja-Confirm) please fallow the mockups while creating any view

**Additional**
I would recommend to use this [Material Text feild](https://github.com/florent37/MaterialTextField) for editTexts

**Would you like to work on the issue?** (Yes/No)
No

**Comment by athiranair2000** [comment]
Hi,Can I work on this issue?

**Comment by ajay-prabhakar** [comment]
yeah thank you for your interest :smile:
