### ISSUE TITLE
Add firebase support

### ISSUE THREAD

**Issue by ajay-prabhakar** [amfoss/temple-app#125]
**Describe the feature you'd like**
Add the firebase support to the app as we discussed that  we are going to use backend as firebase

**Would you like to work on the issue?** (Yes/No)
No

**Comment by NitinKumar26** [comment]
can I work on this?

**Comment by yashk2000** [comment]
Go ahead @NitinKumar26

**Comment by NitinKumar26** [comment]
OK

**Comment by NitinKumar26** [comment]
Thanks for the opportunity!

**Comment by NitinKumar26** [comment]
Hi sir, what exactly do I have to implement in this PR, do I need to fully migrate the project backend to firebase? In that case, what will be the account details of firestore firebase?

**Comment by yashk2000** [comment]
@NitinKumar26 one of our community members already started working on this issue and has made considerable progress. 

Thanks for showing interest!! Keep an eye out for more issues. We look forward to your contributions :smile:

**Comment by yashk2000** [comment]
Issue has been taken care of. Hence closing this :sparkler:
