### ISSUE TITLE
Create a google account 

### ISSUE THREAD

**Issue by ajay-prabhakar** [amfoss/temple-app#126]
**Describe the feature you'd like**
Create a google account for firebase support so we can all see whatever the thing is happening and we can solve easily if there is any error 

**Would you like to work on the issue?** (Yes/No)
No

**Comment by Chromicle** [comment]
Whenever you created the google account please share the credentials here

**Comment by vchrombie** [comment]
I am not sure if this is a good idea. Maybe, we can discuss and get this solved. Let's hold this issue for a while. :)

**Comment by yashk2000** [comment]
This has been done. Therefore closing the issue.
